-- dados_revisada.sql
-- Dataset de Diagnóstico Estudantil: 15 alunos em 3 turmas.
SET search_path TO sc_student_diagnosis, public;

-- 1) USUÁRIOS
INSERT INTO users (name_user, email, password, function) VALUES
  ('admin_jose', 'jose.admin@escola.com', 'hash_admin', 'admin'),
  ('prof_maria', 'maria.prof@escola.com', 'hash_prof', 'professor'),
  ('henrygabriel_sousa', 'henrygabriel.sousa@escola.com', 'hash_aluno', 'aluno'),
  ('yan_camara', 'yan.camara@escola.com', 'hash_aluno', 'aluno'),
  ('joaolucas_caldeira', 'joaolucas.caldeira@escola.com', 'hash_aluno', 'aluno'),
  ('zoe_pastor', 'zoe.pastor@escola.com', 'hash_aluno', 'aluno'),
  ('lavinia_alves', 'lavinia.alves@escola.com', 'hash_aluno', 'aluno'),
  ('francisco_daconceicao', 'francisco.daconceicao@escola.com', 'hash_aluno', 'aluno'),
  ('mirella_alves', 'mirella.alves@escola.com', 'hash_aluno', 'aluno'),
  ('miguel_rezende', 'miguel.rezende@escola.com', 'hash_aluno', 'aluno'),
  ('zoe_camara', 'zoe.camara@escola.com', 'hash_aluno', 'aluno'),
  ('manuela_damota', 'manuela.damota@escola.com', 'hash_aluno', 'aluno'),
  ('anthonygabriel_castro', 'anthonygabriel.castro@escola.com', 'hash_aluno', 'aluno'),
  ('lavinia_damota', 'lavinia.damota@escola.com', 'hash_aluno', 'aluno'),
  ('leonardo_teixeira', 'leonardo.teixeira@escola.com', 'hash_aluno', 'aluno'),
  ('barbara_borges', 'barbara.borges@escola.com', 'hash_aluno', 'aluno'),
  ('gabrielly_fogaca', 'gabrielly.fogaca@escola.com', 'hash_aluno', 'aluno')
ON CONFLICT (email) DO NOTHING;

-- 2) PROFESSORA
INSERT INTO teachers (user_id, full_name, email) VALUES
  ((SELECT id FROM users WHERE email = 'maria.prof@escola.com' LIMIT 1), 'Maria da Silva Santos', 'maria.prof@escola.com')
ON CONFLICT (email) DO NOTHING;

-- 3) ALUNOS
INSERT INTO student (user_id, full_name, email, grade, class) VALUES
  ((SELECT id FROM users WHERE email = 'henrygabriel.sousa@escola.com' LIMIT 1), 'Henry Gabriel Alves Sousa', 'henrygabriel.sousa@escola.com', '8º ano', 'A'),
  ((SELECT id FROM users WHERE email = 'yan.camara@escola.com' LIMIT 1), 'Yan da Cruz Câmara', 'yan.camara@escola.com', '8º ano', 'A'),
  ((SELECT id FROM users WHERE email = 'joaolucas.caldeira@escola.com' LIMIT 1), 'João Lucas Sousa Caldeira', 'joaolucas.caldeira@escola.com', '8º ano', 'A'),
  ((SELECT id FROM users WHERE email = 'zoe.pastor@escola.com' LIMIT 1), 'Zoe Borges Pastor', 'zoe.pastor@escola.com', '8º ano', 'A'),
  ((SELECT id FROM users WHERE email = 'lavinia.alves@escola.com' LIMIT 1), 'Lavínia Andrade Alves', 'lavinia.alves@escola.com', '8º ano', 'A'),
  ((SELECT id FROM users WHERE email = 'francisco.daconceicao@escola.com' LIMIT 1), 'Francisco Cunha da Conceição', 'francisco.daconceicao@escola.com', '8º ano', 'B'),
  ((SELECT id FROM users WHERE email = 'mirella.alves@escola.com' LIMIT 1), 'Mirella Pereira Alves', 'mirella.alves@escola.com', '8º ano', 'B'),
  ((SELECT id FROM users WHERE email = 'miguel.rezende@escola.com' LIMIT 1), 'Miguel Silva Rezende', 'miguel.rezende@escola.com', '8º ano', 'B'),
  ((SELECT id FROM users WHERE email = 'zoe.camara@escola.com' LIMIT 1), 'Zoe Leão Câmara', 'zoe.camara@escola.com', '8º ano', 'B'),
  ((SELECT id FROM users WHERE email = 'manuela.damota@escola.com' LIMIT 1), 'Manuela Pastor da Mota', 'manuela.damota@escola.com', '8º ano', 'B'),
  ((SELECT id FROM users WHERE email = 'anthonygabriel.castro@escola.com' LIMIT 1), 'Anthony Gabriel Teixeira Castro', 'anthonygabriel.castro@escola.com', '9º ano', 'A'),
  ((SELECT id FROM users WHERE email = 'lavinia.damota@escola.com' LIMIT 1), 'Lavínia Fernandes da Mota', 'lavinia.damota@escola.com', '9º ano', 'A'),
  ((SELECT id FROM users WHERE email = 'leonardo.teixeira@escola.com' LIMIT 1), 'Leonardo Cunha Teixeira', 'leonardo.teixeira@escola.com', '9º ano', 'A'),
  ((SELECT id FROM users WHERE email = 'barbara.borges@escola.com' LIMIT 1), 'Bárbara Caldeira Borges', 'barbara.borges@escola.com', '9º ano', 'A'),
  ((SELECT id FROM users WHERE email = 'gabrielly.fogaca@escola.com' LIMIT 1), 'Gabrielly Brito Fogaça', 'gabrielly.fogaca@escola.com', '9º ano', 'A')
ON CONFLICT (email) DO NOTHING;

-- 4) PEDIDOS DE DIAGNÓSTICO
INSERT INTO diagnostic_requests (teacher_id, title, description, grade, class, status) VALUES
  ((SELECT id FROM teachers WHERE email = 'maria.prof@escola.com' LIMIT 1), 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A', 'Mapeamento diagnóstico', '8º ano', 'A', 'aberto'),
  ((SELECT id FROM teachers WHERE email = 'maria.prof@escola.com' LIMIT 1), 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B', 'Mapeamento diagnóstico', '8º ano', 'B', 'aberto'),
  ((SELECT id FROM teachers WHERE email = 'maria.prof@escola.com' LIMIT 1), 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A', 'Mapeamento diagnóstico', '9º ano', 'A', 'aberto')
ON CONFLICT DO NOTHING;

-- 5) RESPOSTAS
INSERT INTO diagnosis_answer (order_id, student_id) VALUES
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), (SELECT id FROM student WHERE email = 'henrygabriel.sousa@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), (SELECT id FROM student WHERE email = 'yan.camara@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), (SELECT id FROM student WHERE email = 'joaolucas.caldeira@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), (SELECT id FROM student WHERE email = 'zoe.pastor@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), (SELECT id FROM student WHERE email = 'lavinia.alves@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), (SELECT id FROM student WHERE email = 'francisco.daconceicao@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), (SELECT id FROM student WHERE email = 'mirella.alves@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), (SELECT id FROM student WHERE email = 'miguel.rezende@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), (SELECT id FROM student WHERE email = 'zoe.camara@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), (SELECT id FROM student WHERE email = 'manuela.damota@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), (SELECT id FROM student WHERE email = 'anthonygabriel.castro@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), (SELECT id FROM student WHERE email = 'lavinia.damota@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), (SELECT id FROM student WHERE email = 'leonardo.teixeira@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), (SELECT id FROM student WHERE email = 'barbara.borges@escola.com' LIMIT 1)),
  ((SELECT id FROM diagnostic_requests WHERE title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), (SELECT id FROM student WHERE email = 'gabrielly.fogaca@escola.com' LIMIT 1))
ON CONFLICT (order_id, student_id) DO NOTHING;

-- 6) DADOS SOCIOECONÔMICOS
INSERT INTO socioeconomic_data (answer_id, family_income, works_besides_studying, work_hours_per_week, parents_education, has_internet_at_home, has_computer_at_home) VALUES
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'henrygabriel.sousa@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Entre 2 e 4 salários mínimos', TRUE, 20, 'Ensino médio incompleto', TRUE, FALSE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'yan.camara@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Entre 2 e 4 salários mínimos', FALSE, NULL, 'Ensino médio incompleto', TRUE, TRUE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'joaolucas.caldeira@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Entre 1 e 2 salários mínimos', FALSE, NULL, 'Ensino superior incompleto', TRUE, FALSE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'zoe.pastor@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Até 1 salário mínimo', TRUE, 40, 'Ensino médio incompleto', TRUE, FALSE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'lavinia.alves@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Entre 2 e 4 salários mínimos', FALSE, NULL, 'Ensino fundamental incompleto', TRUE, TRUE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'francisco.daconceicao@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Entre 4 e 6 salários mínimos', FALSE, NULL, 'Ensino fundamental incompleto', TRUE, FALSE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'mirella.alves@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Entre 1 e 2 salários mínimos', FALSE, NULL, 'Ensino superior completo', FALSE, TRUE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'miguel.rezende@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Até 1 salário mínimo', FALSE, NULL, 'Pós-graduação', TRUE, FALSE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'zoe.camara@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Até 1 salário mínimo', TRUE, 40, 'Ensino médio completo', FALSE, FALSE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'manuela.damota@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Entre 4 e 6 salários mínimos', FALSE, NULL, 'Pós-graduação', TRUE, FALSE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'anthonygabriel.castro@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Até 1 salário mínimo', FALSE, NULL, 'Ensino fundamental completo', TRUE, FALSE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'lavinia.damota@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Até 1 salário mínimo', FALSE, NULL, 'Ensino médio incompleto', TRUE, TRUE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'leonardo.teixeira@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Entre 1 e 2 salários mínimos', FALSE, NULL, 'Pós-graduação', TRUE, TRUE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'barbara.borges@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Entre 2 e 4 salários mínimos', FALSE, NULL, 'Sem escolaridade', TRUE, TRUE),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'gabrielly.fogaca@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Entre 4 e 6 salários mínimos', FALSE, NULL, 'Ensino fundamental incompleto', TRUE, FALSE)
ON CONFLICT (answer_id) DO NOTHING;

-- 7) CONTEXTO CULTURAL
INSERT INTO cultural_context (answer_id, cultural_activities, community_cultural_tradition, role_family_community_training) VALUES
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'henrygabriel.sousa@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Violão, canto e coral da igreja', 'Festa junina da comunidade', 'Envolve a criança nas decisões da casa'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'yan.camara@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Leitura, música e esportes', 'Festas de aniversário comunitárias', 'Apoia a criatividade e a continuidade dos estudos'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'joaolucas.caldeira@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Jogos de tabuleiro e leitura', 'Quadrilha e danças regionais', 'A família valoriza o trabalho e a cooperação'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'zoe.pastor@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Música e artes visuais', 'Festas de aniversário comunitárias', 'A família valoriza o trabalho e a cooperação'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'lavinia.alves@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Música e artes visuais', 'Tradições de origem nordestina', 'Prioriza a estabilidade financeira acima de tudo'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'francisco.daconceicao@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Desenho, cinema e fotografia', 'Tradições de origem nordestina', 'Prioriza a estabilidade financeira acima de tudo'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'mirella.alves@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Música e artes visuais', 'Tradições de origem nordestina', 'Prioriza a estabilidade financeira acima de tudo'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'miguel.rezende@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Leitura, música e esportes', 'Congada e manifestações afro-brasileiras', 'A família valoriza o trabalho e a cooperação'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'zoe.camara@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Violão, canto e coral da igreja', 'Festa junina da comunidade', 'Estimula a leitura e o diálogo em casa'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'manuela.damota@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Esportes coletivos e voluntariado', 'Tradições de origem nordestina', 'Incentiva os estudos e a participação em eventos locais'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'anthonygabriel.castro@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Capoeira e dança folclórica', 'Tradições de origem nordestina', 'Foca em disciplina e responsabilidade'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'lavinia.damota@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Leitura, música e esportes', 'Tradições de origem nordestina', 'A família valoriza o trabalho e a cooperação'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'leonardo.teixeira@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Capoeira e dança folclórica', 'Tradições de origem nordestina', 'A família valoriza o trabalho e a cooperação'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'barbara.borges@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Futebol e jogos digitais', 'Tradições de origem nordestina', 'Foca em disciplina e responsabilidade'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'gabrielly.fogaca@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Leitura, música e esportes', 'Festa junina da comunidade', 'Foca em disciplina e responsabilidade')
ON CONFLICT (answer_id) DO NOTHING;

-- 8) DIMENSÃO POLÍTICA
INSERT INTO political_dimension (answer_id, follows_politics_society_news, participated_in_social_movement, role_education_social_transformation) VALUES
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'henrygabriel.sousa@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), TRUE, TRUE, 'A educação pode melhorar oportunidades e reduzir desigualdades'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'yan.camara@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), FALSE, FALSE, 'A educação pode melhorar oportunidades e reduzir desigualdades'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'joaolucas.caldeira@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), FALSE, FALSE, 'A escola deve preparar para o mercado de trabalho'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'zoe.pastor@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), TRUE, FALSE, 'A escola é fundamental para transformar a sociedade'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'lavinia.alves@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), TRUE, FALSE, 'A escola deve preparar para o mercado de trabalho'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'francisco.daconceicao@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), TRUE, FALSE, 'Educação é a principal ferramenta de ascensão social'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'mirella.alves@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), TRUE, TRUE, 'A educação ajuda a formar cidadãos críticos e conscientes'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'miguel.rezende@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), FALSE, FALSE, 'A escola é fundamental para transformar a sociedade'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'zoe.camara@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), FALSE, FALSE, 'A educação pode melhorar oportunidades e reduzir desigualdades'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'manuela.damota@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), TRUE, FALSE, 'A educação ajuda a formar cidadãos críticos e conscientes'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'anthonygabriel.castro@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), FALSE, FALSE, 'A escola é fundamental para transformar a sociedade'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'lavinia.damota@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), FALSE, FALSE, 'A educação ajuda a formar cidadãos críticos e conscientes'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'leonardo.teixeira@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), TRUE, FALSE, 'Educação é a principal ferramenta de ascensão social'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'barbara.borges@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), TRUE, FALSE, 'Educação é a principal ferramenta de ascensão social'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'gabrielly.fogaca@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), TRUE, FALSE, 'A educação pode melhorar oportunidades e reduzir desigualdades')
ON CONFLICT (answer_id) DO NOTHING;

-- 9) EXPERIÊNCIAS ESCOLARES
INSERT INTO school_experiences (answer_id, teachers_relations, opinion_is_heard_at_school, learning_difficulties) VALUES
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'henrygabriel.sousa@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Difícil, falta diálogo com alguns professores', FALSE, 'Falta de concentração e motivação'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'yan.camara@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Razoável, com alguns conflitos pontuais', FALSE, 'Metodologias muito rápidas em algumas disciplinas'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'joaolucas.caldeira@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Muito boa e acolhedora', FALSE, 'Falta de concentração e motivação'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'zoe.pastor@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Razoável, com alguns conflitos pontuais', TRUE, 'Dificuldade em matemática e falta de materiais'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'lavinia.alves@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Razoável, com alguns conflitos pontuais', FALSE, 'Falta de tempo para estudar em casa'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'francisco.daconceicao@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Razoável, com alguns conflitos pontuais', TRUE, 'Dificuldade em matemática e falta de materiais'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'mirella.alves@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Razoável, com alguns conflitos pontuais', FALSE, 'Falta de apoio familiar nos estudos'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'miguel.rezende@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Regular, depende muito do professor', FALSE, 'Falta de tempo para estudar em casa'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'zoe.camara@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Razoável, com alguns conflitos pontuais', TRUE, 'Dificuldade em matemática e falta de materiais'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'manuela.damota@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Boa e respeitosa', FALSE, 'Falta de tempo para estudar em casa'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'anthonygabriel.castro@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Distante, mas sem grandes problemas', FALSE, 'Conciliar trabalho e escola'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'lavinia.damota@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Difícil, falta diálogo com alguns professores', TRUE, 'Falta de apoio familiar nos estudos'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'leonardo.teixeira@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Distante, mas sem grandes problemas', TRUE, 'Falta de apoio familiar nos estudos'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'barbara.borges@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Razoável, com alguns conflitos pontuais', TRUE, 'Dificuldade em matemática e falta de materiais'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'gabrielly.fogaca@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Regular, depende muito do professor', TRUE, 'Falta de tempo para estudar em casa')
ON CONFLICT (answer_id) DO NOTHING;

-- 10) EXPECTATIVAS E SONHOS
INSERT INTO expectations_dreams (answer_id, personal_professional_goals, support_that_the_school_should_offer) VALUES
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'henrygabriel.sousa@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Concluir os estudos e abrir um negócio próprio', 'Programas de mentoria com profissionais da área'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'yan.camara@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Entrar na universidade e trabalhar com saúde', 'Mais orientação vocacional e reforço escolar'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'joaolucas.caldeira@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Seguir carreira na área de tecnologia', 'Bibliotecas e materiais de qualidade'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'zoe.pastor@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Fazer medicina e ajudar a comunidade', 'Projetos, laboratório de informática e orientação profissional'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'lavinia.alves@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano A' LIMIT 1), 'Concluir os estudos e abrir um negócio próprio', 'Mais orientação vocacional e reforço escolar'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'francisco.daconceicao@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Fazer medicina e ajudar a comunidade', 'Bibliotecas e materiais de qualidade'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'mirella.alves@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Ser professor e contribuir com a educação', 'Bibliotecas e materiais de qualidade'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'miguel.rezende@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Seguir carreira na área de tecnologia', 'Psicólogo escolar e espaço de escuta'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'zoe.camara@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Trabalhar com música e artes', 'Bibliotecas e materiais de qualidade'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'manuela.damota@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 8º ano B' LIMIT 1), 'Trabalhar com música e artes', 'Cursos técnicos e apoio para conciliar estudo e trabalho'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'anthonygabriel.castro@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Entrar na universidade e trabalhar com saúde', 'Cursos técnicos e apoio para conciliar estudo e trabalho'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'lavinia.damota@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Ser professor e contribuir com a educação', 'Cursos técnicos e apoio para conciliar estudo e trabalho'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'leonardo.teixeira@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Entrar na universidade e trabalhar com saúde', 'Programas de mentoria com profissionais da área'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'barbara.borges@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Entrar na universidade e trabalhar com saúde', 'Psicólogo escolar e espaço de escuta'),
  ((SELECT da.id FROM diagnosis_answer da JOIN student s ON da.student_id = s.id JOIN diagnostic_requests p ON da.order_id = p.id WHERE s.email = 'gabrielly.fogaca@escola.com' AND p.title = 'Diagnóstico Inicial 2026 - 1º Bimestre - 9º ano A' LIMIT 1), 'Concluir os estudos e abrir um negócio próprio', 'Psicólogo escolar e espaço de escuta')
ON CONFLICT (answer_id) DO NOTHING;
